In [3]:
import numpy as np

In [4]:
arr = [1,2,3,4]
n = np.array(arr)
print(n)

[1 2 3 4]


In [5]:
# mean of numpy
print(n.mean())
print(type(n))

2.5
<class 'numpy.ndarray'>


In [6]:
l1 = [1,2,3,4,5]
l2 = [6,7,8,9,10]
l3 = [11,12,13,14,15]
D2 = np.array([l1,l2,l3])
print(D2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [10]:
print(D2.shape)
print(type(D2))
# datatype of array
print(D2.dtype)

(3, 5)
<class 'numpy.ndarray'>
int64


In [13]:
# way to make arrays 
text = ["hello", "world"]
a = np.fromiter(text,dtype="U2")
print(a)

['he' 'wo']


In [23]:
# lab experiment
np.random.seed(42)
D2_10 = np.random.randint(0,99,(10,10))
print(D2_10)

[[51 92 14 71 60 20 82 86 74 74]
 [87 23  2 21 52  1 87 29 37  1]
 [63 59 20 32 75 57 21 88 48 90]
 [58 41 91 59 79 14 61 61 46 61]
 [50 54 63  2 50  6 20 72 38 17]
 [ 3 88 59 13  8 89 52  1 83 91]
 [59 70 43  7 46 34 77 80 35 49]
 [ 3  1  5 53  3 53 92 62 17 89]
 [43 33 73 61 13 94 47 14 71 77]
 [86 61 39 84 79 81 52 23 25 88]]


In [ ]:
A = D2_10[0:5, 0:7]
print(A)
B = D2_10[2:9, 3:8]
print(B)

[[51 92 14 71 60 20 82]
 [87 23  2 21 52  1 87]
 [63 59 20 32 75 57 21]
 [58 41 91 59 79 14 61]
 [50 54 63  2 50  6 20]]
[[32 75 57 21 88]
 [59 79 14 61 61]
 [ 2 50  6 20 72]
 [13  8 89 52  1]
 [ 7 46 34 77 80]
 [53  3 53 92 62]
 [61 13 94 47 14]]
